export const mobile_phones = [
  {
    id: 1,
    title: "Samsung Galaxy S10",
    company: "Samsung",
    category: "Mobile Phones",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium harum ipsam maiores excepturi, enim quae ex consectetur magnam quo temporibus error, vel iure eveniet id quas expedita cum cupiditate autem!",
    img: "mobile_phones/samsung-galaxy-s10-1.webp",
    imageWidth: 200,
    imageHeight: 200,
    price: 300,
    hasDiscount: false,
    isInCart: false,
    amountInCart: 0
  },
  {
    id: 2,
    title: "Samsung Galaxy S9",
    company: "Samsung",
    category: "Mobile Phones",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium harum ipsam maiores excepturi, enim quae ex consectetur magnam quo temporibus error, vel iure eveniet id quas expedita cum cupiditate autem!",
    img: "mobile_phones/samsung-galaxy-s9-1.webp",
    imageWidth: 200,
    imageHeight: 200,
    price: 250,
    hasDiscount: false,
    isInCart: false,
    amountInCart: 0
  },
  {
    id: 3,
    title: "Samsung Galaxy S8",
    company: "Samsung",
    category: "Mobile Phones",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium harum ipsam maiores excepturi, enim quae ex consectetur magnam quo temporibus error, vel iure eveniet id quas expedita cum cupiditate autem!",
    img: "mobile_phones/samsung-galaxy-s8-1.webp",
    imageWidth: 200,
    imageHeight: 200,
    price: 300,
    hasDiscount: true,
    isInCart: false,
    amountInCart: 0
  },
  {
    id: 4,
    title: "iPhone X",
    company: "Apple",
    category: "Mobile Phones",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium harum ipsam maiores excepturi, enim quae ex consectetur magnam quo temporibus error, vel iure eveniet id quas expedita cum cupiditate autem!",
    img: "mobile_phones/iphone-x-1.webp",
    imageWidth: 200,
    imageHeight: 200,
    price: 300,
    hasDiscount: false,
    isInCart: false,
    amountInCart: 0
  },
  {
    id: 5,
    title: "iPhone XR",
    company: "Apple",
    category: "Mobile Phones",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium harum ipsam maiores excepturi, enim quae ex consectetur magnam quo temporibus error, vel iure eveniet id quas expedita cum cupiditate autem!",
    img: "mobile_phones/iphone-xr-1.webp",
    imageWidth: 200,
    imageHeight: 200,
    price: 250,
    hasDiscount: false,
    isInCart: false,
    amountInCart: 0
  },
  {
    id: 6,
    title: "iPhone XS",
    company: "Apple",
    category: "Mobile Phones",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium harum ipsam maiores excepturi, enim quae ex consectetur magnam quo temporibus error, vel iure eveniet id quas expedita cum cupiditate autem!",
    img: "mobile_phones/iphone-xs-1.webp",
    imageWidth: 200,
    imageHeight: 200,
    price: 300,
    hasDiscount: true,
    isInCart: false,
    amountInCart: 0
  },
  {
    id: 7,
    title: "Sony Xperia 1",
    company: "Sony",
    category: "Mobile Phones",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium harum ipsam maiores excepturi, enim quae ex consectetur magnam quo temporibus error, vel iure eveniet id quas expedita cum cupiditate autem!",
    img: "mobile_phones/sony-xperia-1-1.webp",
    imageWidth: 200,
    imageHeight: 200,
    price: 300,
    hasDiscount: false,
    isInCart: false,
    amountInCart: 0
  },
  {
    id: 8,
    title: "Sony Xperia XZ2",
    company: "Sony",
    category: "Mobile Phones",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium harum ipsam maiores excepturi, enim quae ex consectetur magnam quo temporibus error, vel iure eveniet id quas expedita cum cupiditate autem!",
    img: "mobile_phones/sony-xperia-xz2-1.webp",
    imageWidth: 200,
    imageHeight: 200,
    price: 250,
    hasDiscount: false,
    isInCart: false,
    amountInCart: 0
  },
  {
    id: 9,
    title: "Sony Xperia XZ3",
    company: "Sony",
    category: "Mobile Phones",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium harum ipsam maiores excepturi, enim quae ex consectetur magnam quo temporibus error, vel iure eveniet id quas expedita cum cupiditate autem!",
    img: "mobile_phones/sony-xperia-xz3-1.webp",
    imageWidth: 200,
    imageHeight: 200,
    price: 300,
    hasDiscount: true,
    isInCart: false,
    amountInCart: 0
  },
  {
    id: 10,
    title: "Xiaomi Redmi 7",
    company: "Xiaomi",
    category: "Mobile Phones",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium harum ipsam maiores excepturi, enim quae ex consectetur magnam quo temporibus error, vel iure eveniet id quas expedita cum cupiditate autem!",
    img: "mobile_phones/xiaomi-redmi-7-1.webp",
    imageWidth: 200,
    imageHeight: 200,
    price: 300,
    hasDiscount: false,
    isInCart: false,
    amountInCart: 0
  },
  {
    id: 11,
    title: "Xiaomi Redmi 6",
    company: "Xiaomi",
    category: "Mobile Phones",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium harum ipsam maiores excepturi, enim quae ex consectetur magnam quo temporibus error, vel iure eveniet id quas expedita cum cupiditate autem!",
    img: "mobile_phones/xiaomi-redmi-6-1.webp",
    imageWidth: 200,
    imageHeight: 200,
    price: 250,
    hasDiscount: false,
    isInCart: false,
    amountInCart: 0
  },
  {
    id: 12,
    title: "Xiaomi Redmi 5",
    company: "Xiaomi",
    category: "Mobile Phones",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium harum ipsam maiores excepturi, enim quae ex consectetur magnam quo temporibus error, vel iure eveniet id quas expedita cum cupiditate autem!",
    img: "mobile_phones/xiaomi-redmi-5-1.webp",
    imageWidth: 200,
    imageHeight: 200,
    price: 300,
    hasDiscount: true,
    isInCart: false,
    amountInCart: 0
  },
  {
    id: 13,
    title: "Huawei P30",
    company: "Huawei",
    category: "Mobile Phones",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium harum ipsam maiores excepturi, enim quae ex consectetur magnam quo temporibus error, vel iure eveniet id quas expedita cum cupiditate autem!",
    img: "mobile_phones/huawei-p30-1.webp",
    imageWidth: 200,
    imageHeight: 200,
    price: 300,
    hasDiscount: false,
    isInCart: false,
    amountInCart: 0
  },
  {
    id: 14,
    title: "Huawei P20",
    company: "Huawei",
    category: "Mobile Phones",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium harum ipsam maiores excepturi, enim quae ex consectetur magnam quo temporibus error, vel iure eveniet id quas expedita cum cupiditate autem!",
    "img": "mobile_phones/huawei-p20-1.webp",
    "imageWidth": 200,
    imageHeight: 200,
    price: 250,
    hasDiscount: false,
    isInCart: false,
    amountInCart: 0
  },
  {
    id: 15,
    title: "Huawei P10",
    company: "Huawei",
    category: "Mobile Phones",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium harum ipsam maiores excepturi, enim quae ex consectetur magnam quo temporibus error, vel iure eveniet id quas expedita cum cupiditate autem!",
    img: "mobile_phones/huawei-p10-1.webp",
    imageWidth: 200,
    imageHeight: 200,
    price: 300,
    hasDiscount: true,
    isInCart: false,
    amountInCart: 0
  }
];

export const laptops = [
  {
    id: 16,
    title: "Acer Aspire 3",
    company: "Acer",
    category: "Laptops",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium harum ipsam maiores excepturi, enim quae ex consectetur magnam quo temporibus error, vel iure eveniet id quas expedita cum cupiditate autem!",
    img: "laptops/acer-aspire-3-1.webp",
    imageWidth: 200,
    imageHeight: 200,
    price: 300,
    hasDiscount: true,
    isInCart: false,
    amountInCart: 0
  },
  {
    id: 17,
    title: "Acer Aspire 5",
    company: "Acer",
    category: "Laptops",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium harum ipsam maiores excepturi, enim quae ex consectetur magnam quo temporibus error, vel iure eveniet id quas expedita cum cupiditate autem!",
    img: "laptops/acer-aspire-5-1.webp",
    imageWidth: 200,
    imageHeight: 200,
    price: 250,
    hasDiscount: false,
    isInCart: false,
    amountInCart: 0
  },
  {
    id: 18,
    title: "Acer Aspire 7",
    company: "Acer",
    category: "Laptops",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium harum ipsam maiores excepturi, enim quae ex consectetur magnam quo temporibus error, vel iure eveniet id quas expedita cum cupiditate autem!",
    img: "laptops/acer-aspire-7-1.webp",
    imageWidth: 200,
    imageHeight: 200,
    price: 300,
    hasDiscount: false,
    isInCart: false,
    amountInCart: 0
  },
  {
    id: 19,
    title: "Apple Macbook Air",
    company: "Apple",
    category: "Laptops",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium harum ipsam maiores excepturi, enim quae ex consectetur magnam quo temporibus error, vel iure eveniet id quas expedita cum cupiditate autem!",
    img: "laptops/apple-macbook-air-1.webp",
    imageWidth: 200,
    imageHeight: 200,
    price: 200,
    hasDiscount: true,
    isInCart: false,
    amountInCart: 0
  },
  {
    id: 20,
    title: "Apple Macbook Pro",
    company: "Apple",
    category: "Laptops",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium harum ipsam maiores excepturi, enim quae ex consectetur magnam quo temporibus error, vel iure eveniet id quas expedita cum cupiditate autem!",
    img: "laptops/apple-macbook-pro-1.webp",
    imageWidth: 200,
    imageHeight: 200,
    price: 300,
    hasDiscount: false,
    isInCart: false,
    amountInCart: 0
  },
  {
    id: 21,
    title: "AsusPro-P5440",
    company: "Asus",
    category: "Laptops",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium harum ipsam maiores excepturi, enim quae ex consectetur magnam quo temporibus error, vel iure eveniet id quas expedita cum cupiditate autem!",
    img: "laptops/asuspro-p5440-1.webp",
    imageWidth: 200,
    imageHeight: 200,
    price: 300,
    hasDiscount: false,
    isInCart: false,
    amountInCart: 0
  },
  {
    id: 22,
    title: "Asus Vivobook S15",
    company: "Asus",
    category: "Laptops",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium harum ipsam maiores excepturi, enim quae ex consectetur magnam quo temporibus error, vel iure eveniet id quas expedita cum cupiditate autem!",
    img: "laptops/asus-vivobook-s15-1.webp",
    imageWidth: 200,
    imageHeight: 200,
    price: 250,
    hasDiscount: true,
    isInCart: false,
    amountInCart: 0
  },
  {
    id: 23,
    title: "Asus Zenbook S UX391",
    company: "Asus",
    category: "Laptops",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium harum ipsam maiores excepturi, enim quae ex consectetur magnam quo temporibus error, vel iure eveniet id quas expedita cum cupiditate autem!",
    img: "laptops/asus-zenbook-s-ux391-1.webp",
    imageWidth: 200,
    imageHeight: 200,
    price: 300,
    hasDiscount: false,
    isInCart: false,
    amountInCart: 0
  },
  {
    id: 24,
    title: "Dell Latitude 7400",
    company: "Dell",
    category: "Laptops",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium harum ipsam maiores excepturi, enim quae ex consectetur magnam quo temporibus error, vel iure eveniet id quas expedita cum cupiditate autem!",
    img: "laptops/dell-latitude-7400-1.webp",
    imageWidth: 200,
    imageHeight: 200,
    price: 200,
    hasDiscount: true,
    isInCart: false,
    amountInCart: 0
  },
  {
    id: 25,
    title: "Dell Vostro 15 5000",
    company: "Dell",
    category: "Laptops",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium harum ipsam maiores excepturi, enim quae ex consectetur magnam quo temporibus error, vel iure eveniet id quas expedita cum cupiditate autem!",
    img: "laptops/dell-vostro-15-5000-5581-1.webp",
    imageWidth: 200,
    imageHeight: 200,
    price: 300,
    hasDiscount: false,
    isInCart: false,
    amountInCart: 0
  },
  {
    id: 26,
    title: "HP Elitebook 850 G5",
    company: "HP",
    category: "Laptops",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium harum ipsam maiores excepturi, enim quae ex consectetur magnam quo temporibus error, vel iure eveniet id quas expedita cum cupiditate autem!",
    img: "laptops/hp-elitebook-850-g5-1.webp",
    imageWidth: 200,
    imageHeight: 200,
    price: 300,
    hasDiscount: true,
    isInCart: false,
    amountInCart: 0
  },
  {
    id: 27,
    title: "HP Probook 650 G1",
    company: "HP",
    category: "Laptops",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium harum ipsam maiores excepturi, enim quae ex consectetur magnam quo temporibus error, vel iure eveniet id quas expedita cum cupiditate autem!",
    img: "laptops/hp-probook-650-g1-1.webp",
    imageWidth: 200,
    imageHeight: 200,
    price: 200,
    hasDiscount: false,
    isInCart: false,
    amountInCart: 0
  },
  {
    id: 28,
    title: "MSI GL63 9SE",
    company: "MSI",
    category: "Laptops",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium harum ipsam maiores excepturi, enim quae ex consectetur magnam quo temporibus error, vel iure eveniet id quas expedita cum cupiditate autem!",
    img: "laptops/msi-gl63-9se-1.webp",
    imageWidth: 200,
    imageHeight: 200,
    price: 200,
    hasDiscount: true,
    isInCart: false,
    amountInCart: 0
  },
  {
    id: 29,
    title: "MSI GL73 8RC 408CA",
    company: "MSI",
    category: "Laptops",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium harum ipsam maiores excepturi, enim quae ex consectetur magnam quo temporibus error, vel iure eveniet id quas expedita cum cupiditate autem!",
    "img": "laptops/msi-gl73-8rc-408ca-1.webp",
    "imageWidth": 200,
    imageHeight: 200,
    price: 300,
    hasDiscount: false,
    isInCart: false,
    amountInCart: 0
  },
  {
    id: 30,
    title: "Razer Blade Pro",
    company: "Razer",
    category: "Laptops",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium harum ipsam maiores excepturi, enim quae ex consectetur magnam quo temporibus error, vel iure eveniet id quas expedita cum cupiditate autem!",
    img: "laptops/razer-blade-pro-1.webp",
    imageWidth: 200,
    imageHeight: 200,
    price: 300,
    hasDiscount: false,
    isInCart: false,
    amountInCart: 0
  },
  {
    id: 31,
    title: "Razer Blade Stealth",
    company: "Razer",
    category: "Laptops",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium harum ipsam maiores excepturi, enim quae ex consectetur magnam quo temporibus error, vel iure eveniet id quas expedita cum cupiditate autem!",
    img: "laptops/razer-blade-stealth-1.webp",
    imageWidth: 200,
    imageHeight: 200,
    price: 200,
    hasDiscount: true,
    isInCart: false,
    amountInCart: 0
  }
];

export const tablets = [
  {
    id: 32,
    title: "Apple iPad Air 2",
    company: "Apple",
    category: "Tablets",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium harum ipsam maiores excepturi, enim quae ex consectetur magnam quo temporibus error, vel iure eveniet id quas expedita cum cupiditate autem!",
    img: "tablets/apple-ipad-air-2-1.webp",
    imageWidth: 200,
    imageHeight: 200,
    price: 200,
    hasDiscount: true,
    isInCart: false,
    amountInCart: 0
  },
  {
    id: 33,
    title: "Apple iPad Pro 11",
    company: "Apple",
    category: "Tablets",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium harum ipsam maiores excepturi, enim quae ex consectetur magnam quo temporibus error, vel iure eveniet id quas expedita cum cupiditate autem!",
    img: "tablets/apple-ipad-pro-11-1.webp",
    imageWidth: 200,
    imageHeight: 200,
    price: 300,
    hasDiscount: false,
    isInCart: false,
    amountInCart: 0
  },
  {
    id: 34,
    title: "BQ-7036L",
    company: "BQ",
    category: "Tablets",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium harum ipsam maiores excepturi, enim quae ex consectetur magnam quo temporibus error, vel iure eveniet id quas expedita cum cupiditate autem!",
    img: "tablets/bq-7036l-1.webp",
    imageWidth: 200,
    imageHeight: 200,
    price: 200,
    hasDiscount: true,
    isInCart: false,
    amountInCart: 0
  },
  {
    id: 35,
    title: "BQ-8067L",
    company: "BQ",
    category: "Tablets",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium harum ipsam maiores excepturi, enim quae ex consectetur magnam quo temporibus error, vel iure eveniet id quas expedita cum cupiditate autem!",
    img: "tablets/bq-8067l-1.webp",
    imageWidth: 200,
    imageHeight: 200,
    price: 300,
    hasDiscount: false,
    isInCart: false,
    amountInCart: 0
  },
  {
    id: 36,
    title: "Huawei Mediapad M5 Lite 8",
    company: "Huawei",
    category: "Tablets",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium harum ipsam maiores excepturi, enim quae ex consectetur magnam quo temporibus error, vel iure eveniet id quas expedita cum cupiditate autem!",
    img: "tablets/huawei-mediapad-m5-lite-8-1.webp",
    imageWidth: 200,
    imageHeight: 200,
    price: 200,
    hasDiscount: true,
    isInCart: false,
    amountInCart: 0
  },
  {
    id: 37,
    title: "Huawei Mediapad T5 10",
    company: "Huawei",
    category: "Tablets",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium harum ipsam maiores excepturi, enim quae ex consectetur magnam quo temporibus error, vel iure eveniet id quas expedita cum cupiditate autem!",
    img: "tablets/huawei-mediapad-t5-10-1.webp",
    imageWidth: 200,
    imageHeight: 200,
    price: 300,
    hasDiscount: false,
    isInCart: false,
    amountInCart: 0
  },
  {
    id: 38,
    title: "Lenovo Tab 4 Plus TB X704F",
    company: "Lenovo",
    category: "Tablets",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium harum ipsam maiores excepturi, enim quae ex consectetur magnam quo temporibus error, vel iure eveniet id quas expedita cum cupiditate autem!",
    img: "tablets/lenovo-tab-4-plus-tb-x704f-1.webp",
    imageWidth: 200,
    imageHeight: 200,
    price: 200,
    hasDiscount: true,
    isInCart: false,
    amountInCart: 0
  },
  {
    id: 39,
    title: "Lenovo Tab E10 TB X104L",
    company: "Lenovo",
    category: "Tablets",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium harum ipsam maiores excepturi, enim quae ex consectetur magnam quo temporibus error, vel iure eveniet id quas expedita cum cupiditate autem!",
    img: "tablets/lenovo-tab-e10-tb-x104l-1.webp",
    imageWidth: 200,
    imageHeight: 200,
    price: 300,
    hasDiscount: false,
    isInCart: false,
    amountInCart: 0
  },
  {
    id: 40,
    title: "Microsoft Surface Go",
    company: "Microsoft",
    category: "Tablets",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium harum ipsam maiores excepturi, enim quae ex consectetur magnam quo temporibus error, vel iure eveniet id quas expedita cum cupiditate autem!",
    img: "tablets/microsoft-surface-go-1.webp",
    imageWidth: 200,
    imageHeight: 200,
    price: 200,
    hasDiscount: true,
    isInCart: false,
    amountInCart: 0
  },
  {
    id: 41,
    title: "Microsoft Surface Pro 6",
    company: "Microsoft",
    category: "Tablets",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium harum ipsam maiores excepturi, enim quae ex consectetur magnam quo temporibus error, vel iure eveniet id quas expedita cum cupiditate autem!",
    img: "tablets/microsoft-surface-pro-6-1.webp",
    imageWidth: 200,
    imageHeight: 200,
    price: 300,
    hasDiscount: false,
    isInCart: false,
    amountInCart: 0
  },
  {
    id: 42,
    title: "Samsung Galaxy Tab A101",
    company: "Samsung",
    category: "Tablets",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium harum ipsam maiores excepturi, enim quae ex consectetur magnam quo temporibus error, vel iure eveniet id quas expedita cum cupiditate autem!",
    img: "tablets/samsung-galaxy-tab-a-101-1.webp",
    imageWidth: 200,
    imageHeight: 200,
    price: 200,
    hasDiscount: true,
    isInCart: false,
    amountInCart: 0
  },
  {
    id: 43,
    title: "Samsung Galaxy Tab S6 T860",
    company: "Samsung",
    category: "Tablets",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium harum ipsam maiores excepturi, enim quae ex consectetur magnam quo temporibus error, vel iure eveniet id quas expedita cum cupiditate autem!",
    img: "tablets/samsung-galaxy-tab-s6-t860-1.webp",
    imageWidth: 200,
    imageHeight: 200,
    price: 300,
    hasDiscount: false,
    isInCart: false,
    amountInCart: 0
  },
  {
    id: 44,
    title: "Xiaomi Mipad 4",
    company: "Xiaomi",
    category: "Tablets",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium harum ipsam maiores excepturi, enim quae ex consectetur magnam quo temporibus error, vel iure eveniet id quas expedita cum cupiditate autem!",
    img: "tablets/xiaomi-mipad-4-1.webp",
    imageWidth: 200,
    imageHeight: 200,
    price: 300,
    hasDiscount: true,
    isInCart: false,
    amountInCart: 0
  },
  {
    id: 45,
    title: "Xiaomi Mipad 4 Plus",
    company: "Xiaomi",
    category: "Tablets",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium harum ipsam maiores excepturi, enim quae ex consectetur magnam quo temporibus error, vel iure eveniet id quas expedita cum cupiditate autem!",
    img: "tablets/xiaomi-mipad-4-plus-1.webp",
    imageWidth: 200,
    imageHeight: 200,
    price: 200,
    hasDiscount: false,
    isInCart: false,
    amountInCart: 0
  }
];

export const data = [
  ...mobile_phones,
  ...laptops,
  ...tablets
];

export const productTemplate = {
  id: 1,
  title: "Samsung Galaxy S10",
  company: "Samsung",
  description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium harum ipsam maiores excepturi, enim quae ex consectetur magnam quo temporibus error, vel iure eveniet id quas expedita cum cupiditate autem!",
  img: "samsung-galaxy-s10-1.webp",
  imageWidth: 200,
  imageHeight: 200,
  price: 300,
  isInCart: false,
  amountInCart: 0
};
